services: 
  apache:
    build:
      context: .
    container_name: apache
    restart: always
    ports:
      - "80:80"
    volumes:
      - "./www:/var/www"
      - "./etc/sites-available:/etc/apache2/sites-available"
      - "./etc/log:/dev/log"
    links:
      - db
  db:
    image: mysql:5.7
    container_name: mysql
    ports:
    - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: suporte123
      MYSQL_DATABASE: site
    volumes:
      - "./database:/var/lib/mysql"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1